Dev 43
marfatech/api-platform-bundle pull request #5
Opened 2022-05-17 21:33 UTC by iamskey

2022-05-18 15:29 UTC, revilon1991 commented on .github/workflows/phpunit.yaml
> +          symfony/http-kernel:${{ matrix.symfony-versions }} \
- [ ] вместо перечислений пакетов лучше использовать подход, который предлагает симфони при тестировании через CI matrix

см https://symfony.com/doc/current/bundles/best_practices.html#require-a-specific-symfony-version

2022-05-18 15:36 UTC, revilon1991 commented on Tests/AppTestKernel.php
> +        return sys_get_temp_dir() . '/MarfaTechApiPlatformBundle/logs';
- [ ] нужно добавить нативные функции в блок use

2022-05-18 15:40 UTC, revilon1991 commented on Tests/Factory/ApiDtoFactoryTest.php
> +    protected ContainerInterface $container;
Не критично, но я бы рекомендовал не использова контейнер в тестах и собирать зависимости руками через `new SomeService($firstDependency, $secondDependency)`. Это много кратно повышает производительность и облегчает обвязку тестов.
Так делал в [DbalBundle](https://github.com/marfatech/dbal-bundle/tree/master/Tests) и для 89 тестов от начала запуска тестов до полного прохода требуется примерно 1/10 секунды.

2022-05-18 16:56 UTC, revilon1991 commented
- [ ] Также можно удалить BC [костыль](https://github.com/marfatech/api-platform-bundle/blob/master/DependencyInjection/Configuration.php#L39) для версий sf < 4.1

2022-05-20 09:33 UTC, iamskey commented on HttpFoundation/ApiRequest.php
> +    public function get($key, $default = null): mixed
Этот метод наследуется из `Symfony\Component\HttpFoundation\Reqeust`, его тип меняется в соответствии с типизацией sf6

2022-05-20 13:59 UTC, revilon1991 requested changes

2022-05-20 13:59 UTC, revilon1991 commented on Tests/AppTestKernel.php
> +use function sys_get_temp_dir;
```suggestion
use function in_array;
use function sys_get_temp_dir;
```

2022-05-20 13:59 UTC, revilon1991 commented on Tests/Factory/ApiDtoResolverFactoryTest.php
> +        self::assertSame( 'testString', $dto->getString());
```suggestion
        self::assertSame('testString', $dto->getString());
```

2022-05-20 13:59 UTC, revilon1991 commented on HttpFoundation/ApiRequest.php
> +    public function get($key, $default = null): mixed
мы могли бы так сделать, если бы не поддерживали sf4/5 где .

кто-то кто использует проект на 5ой симфони имел право проставить свой тип в дочернем классе `ApiRequest` и после обновления у него сломается код.

2022-05-23 12:46 UTC, iamskey commented on HttpFoundation/ApiRequest.php
> +    public function get($key, $default = null): mixed
[mixed](https://www.php.net/manual/ru/language.types.declarations.php#language.types.declarations.mixed) эквивалентен [объединению типов](https://www.php.net/manual/ru/language.types.declarations.php#language.types.declarations.composite.union) `object|resource|array|string|int|float|bool|null`

[пример](https://onlinephp.io?s=s7EvyCjg5eLlSs5JLC5WcFSo5uXiTCvNSy7JzM9TKEktLtHQtFLIzaxITQFKgCQ5gbiWl6sWoclJIbWiJDUvBaf2zLwSnJqdCWl2RNMKAA%2C%2C&v=8.1.6)

2022-05-23 13:03 UTC, revilon1991 commented on HttpFoundation/ApiRequest.php
> +    public function get($key, $default = null): mixed
ну пользователям тогда хотя бы какой-то тип нужно иметь в декларации метода, а если у них ничего не стояло, то будет ошибка
```php
<?php

// декорация со стороны пользователя бандла
class ApiRequestDecorate extends ApiRequest
{
    public function get($key, $default = null)
    {
        return 1;
    }
}

// класс в бандле
class ApiRequest
{
    public function get($key, $default = null): mixed
    {
        return 1;
    }
}

new ApiRequest();

// Fatal error: Declaration of ApiRequestDecorate::get($key, $default = null) must be compatible with ApiRequest::get($key, $default = null): mixed
```

2022-05-24 14:35 UTC, revilon1991 requested changes

2022-05-24 14:35 UTC, revilon1991 commented on HttpFoundation/ApiRequestOld.php
> +    ): static {
- [ ] нужно вернуть self для sf4/5 иначе будет fatal error для пользователй бандла, которые проставили self return type

2022-05-24 14:42 UTC, revilon1991 approved these changes

2022-05-24 14:43 UTC, merged